<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.veracode</groupId>
	<artifactId>verademo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>verademo</name>
	<url>https://github.com/veracode/verademo</url>
	<packaging>war</packaging>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.1.RELEASE</version>
		<relativePath/>
	</parent>

	<!-- Component Version Properties -->
	<properties>
		<spring.version>4.3.10.RELEASE</spring.version>
		<springboot.version>2.3.1.RELEASE</springboot.version>
		<fileupload.version>1.3.2</fileupload.version>
	</properties>
	<!-- Dependency Management to pin transitive dependencies to safe versions -->
	<dependencyManagement>
		<dependencies>
			<!-- Pin tomcat-embed-core to safe version: CVE-2020-13934, CVE-2020-13943, CVE-2020-17527, CVE-2021-24122, CVE-2021-25122, CVE-2021-25329, CVE-2021-30640, CVE-2021-33037, CVE-2022-23181, CVE-2022-42252, CVE-2023-24998, CVE-2023-28709, CVE-2023-41080, CVE-2023-45648, CVE-2023-42795, CVE-2023-44487, CVE-2023-46589, CVE-2024-21733, CVE-2024-24549, CVE-2024-34750, CVE-2024-38286, CVE-2024-52316, CVE-2024-50379, CVE-2024-56337, CVE-2025-24813, CVE-2025-31651, CVE-2025-46701, CVE-2025-49125, CVE-2025-48988, CVE-2025-52434, CVE-2025-52520, CVE-2025-53506, CVE-2025-48989, CVE-2025-55668, CVE-2025-55752, CVE-2025-61795, CVE-2025-66614, CVE-2026-24880, CVE-2026-25854, CVE-2026-34487, CVE-2026-42498, CVE-2026-43512, CVE-2026-43515, CVE-2026-43513, CVE-2026-41293, CVE-2026-43514, CVE-2026-41284, CVE-2026-68525, CVE-2026-65182 -->
			<!-- Spring Boot 2.3.1.RELEASE brings vulnerable tomcat-embed-core 9.0.36 -->
			<!-- Remove when Spring Boot is upgraded to a version that includes a safe transitive -->
			<dependency>
				<groupId>org.apache.tomcat.embed</groupId>
				<artifactId>tomcat-embed-core</artifactId>
				<version>9.0.122</version>
			</dependency>
		</dependencies>
	</dependencyManagement>


	<!-- Dependencies begin here -->
	<dependencies>
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-jasper</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jstl</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>com.veracode.annotation</groupId>
			<artifactId>VeracodeAnnotations</artifactId>
			<version>[1.0.4,)</version>
		</dependency>
		<dependency>
			<groupId>org.owasp.encoder</groupId>
			<artifactId>encoder</artifactId>
			<version>1.2.2</version>
		</dependency>
		<dependency>
			<groupId>org.owasp.encoder</groupId>
			<artifactId>encoder-jsp</artifactId>
			<version>1.2.2</version>
		</dependency>

		<!-- Spring dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<version>${springboot.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<version>${springboot.version}</version>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<version>${springboot.version}</version>
			<scope>provided</scope>
		</dependency>

		<!-- Logging dependencies -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.7</version>
		</dependency>

		<!-- Apache Commons dependencies -->
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>${fileupload.version}</version>
		</dependency>

		<!-- Apache Commons IO -->
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.14.0</version>
		</dependency>

		<!-- Vuln Method libs -->
		<dependency>
			<groupId>org.apache.sling</groupId>
			<artifactId>maven-sling-plugin</artifactId>
			<version>2.0.4-incubator</version>
		</dependency>

		<dependency>
			<groupId>org.mindrot</groupId>
			<artifactId>jbcrypt</artifactId>
			<version>0.3m</version>
		</dependency>

		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-saml-core</artifactId>
			<version>1.8.1.Final</version>
		</dependency>

		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.48</version>
		</dependency>

		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4.7</version>
		</dependency>
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
			<version>4.0</version>
		</dependency>
	</dependencies>

	<build>
		<finalName>verademo</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<debug>true</debug>
					<debuglevel>lines,vars,source</debuglevel>
					<compilerargs>
						<arg>-g:source,lines,vars</arg>
					</compilerargs>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
